### PR TITLE
Add task to remove labels

### PR DESCRIPTION
**Pull request by genkiroid**
Hi. I want to remove labels when the branch has been merged and released.

### CODE REVIEW

**Comment by linyows** [comment]
@genkiroid Why would you need?

**Comment by genkiroid** [comment]
@linyows 

In my team, we are using labels for notification about state of P/R. For example, we add "needs-review" label when we need code review.
After merged into master and released, labels is no necessary. Thus we are manually removing label.

It is slightly costly.

**Comment by linyows** [comment]
Oh I get it.

**Comment by linyows** [comment]
@genkiroid I released as v0.5.0.

**Comment by genkiroid** [comment]
Thanks!!

**Pull request merged**
